modLoader="javafml"
loaderVersion="[41,)"
license="MIT"

[[mods]]
    modId="stackedblocks"
    version="24.11.20-1.19-forge"
    displayName="Stacked Blocks"
    authors="Axperty"
    description="A mod that adds stacked blocks to the game."
    logoFile="assets/stackedblocks/logo.png"

[[dependencies.stackedblocks]]
    modId="forge"
    mandatory=true
    versionRange="[41.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stackedblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
